version: "3"
services:
  server:
    container_name: server
    build: ./server
    working_dir: /app/server
    # volumes:
    #   - ./server:/app/server
    command: ["ls"]
    command: ["npm", "run", "dev-server"]
    environment:
      MONGOLAB_URI: "mongodb://root:root_password@mongodb"
    depends_on:
      - mongodb

  client:
    container_name: client
    build: ./client
    working_dir: /app/client
    volumes:
      - ./client/src:/app/client/src
    command: ["npm", "run", "dev-client"]
    depends_on:
      - server

  mongodb:
    image: mongo:3.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: todo-app
    volumes:
      - mongodata:/data/db
      
  
  nginx: 
    image: nginx:1.17.6
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

volumes:
  mongodata:
